# Generated by Django 3.1.1 on 2020-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='count_of_articles',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
